### ISSUE TITLE
Missing performance tests in question schemas

### ISSUE THREAD

**Issue by seanlip** [google/tie#255]
Due to limitations of the current performance test framework, the following question schemas are missing performance tests:

- [ ] Find best meeting point in grid-like city -- nonlinear (#197)
- [ ] Unknown alphabet -- O(m) (#188)
- [ ] Sort scrambled itinerary -- quadratic (#182)
- [ ] Strobogrammatic numbers -- exponential (#181)

**Comment by seanlip** [comment]
Closing for now; we'll add performance tests as we tidy up questions.
